SELECT USERS.NAME,
       SUM(TRANSACTIONS.AMOUNT) AS BALANCE
FROM USERS
JOIN TRANSACTIONS
ON USERS.ACCOUNT = TRANSACTIONS.ACCOUNT
GROUP BY USERS.ACCOUNT, USERS.NAME
HAVING SUM(TRANSACTIONS.AMOUNT) > 10000;